Added InfluxDB page and removed some first-person language
sdr-enthusiasts/gitbook-adsb-guide pull request #71
Opened 2023-02-18 03:22 UTC by wandering-andy

Should close issue #59. Mostly just took info from main README and put it in one place. I also edited some pages to reduce first-person language.

2023-02-18 12:55 UTC, mikenye requested changes
Thanks so much for your contribution! The addition of the InfluxDB stuff is just fantastic.

If you're able to take a look at the review commends and change accordingly, I will merge this PR.

Thanks again.

2023-02-18 12:55 UTC, mikenye commented on feeder-containers/feeding-flightradar24.md
> +[@mikenye](https://github.com/mikenye) created a docker image [`ghcr.io/sdr-enthusiasts/docker-flightradar24`](https://github.com/sdr-enthusiasts/docker-flightradar24) that contains `fr24feed` and al
Happy for this to be "We".

While I originally created the image, there's been many contributions since then and it is now truly a community effort. :)

2023-02-18 12:55 UTC, mikenye commented on feeder-containers/feeding-flightradar24.md
> +There's an automated script that you can run, however if this breaks \(please let [@mikenye](https://github.com/mikenye) know so he can fix it\), you can also use the manual sign-up method.
Likewise, "please let us know (by raising a GitHub issue) so we can fix it" or similar.

2023-02-18 12:55 UTC, mikenye commented on feeder-containers/feeding-radarbox.md
> +[@mikenye](https://github.com/mikenye) really likes their visualisation. He says overlaying the flight data with precipitation and cloud cover looks fantastic.
This line can probably be removed. I don't really wish to give preference to any of the commercial feeders any more.

2023-02-18 12:55 UTC, mikenye commented on foundations/common-tasks-and-info.md
> +Where practical, [@mikenye](https://github.com/mikenye) tries to include healthchecks in all his images, so as you go through this guide and deploy more containers, you should see a health status whe
As-per previous comments, something like "Where practical, we try to include healthchecks in all of our images..."

2023-02-18 18:45 UTC, wandering-andy commented
Fixed those lines you requested along with some more I/We switches. `equipment-needed.md` still has a lot of your old language in it. It'll probably need a full re-write. I also think `install-docker-compose.md` is outdated as `docker-install.sh` installs `docker compose` directly now, not in a container?

2023-02-20 08:21 UTC, mikenye commented
Thanks!

> `equipment-needed.md` still has a lot of your old language in it. It'll probably need a full re-write.
Yes it will.

> I also think `install-docker-compose.md` is outdated as `docker-install.sh` installs `docker compose` directly now, not in a container?
This is also correct.

Were you going to update these as part of this PR? If so I'll hold off merging it. If not, no problems I can merge these and those other changes can be done separately by you or someone else.

2023-02-20 08:23 UTC, mikenye requested changes

2023-02-20 08:23 UTC, mikenye commented on setting-up-the-host-system/install-docker-compose.md
> +Compose can be run as a container, which we highly recommend. The clever folks over at [linuxserver.io](https://www.linuxserver.io) have a great image that's easily installed.
As you pointed out, this is no longer relevant now that docker compose v2 exists...

2023-02-20 17:59 UTC, wandering-andy commented on setting-up-the-host-system/install-docker-compose.md
> +Compose can be run as a container, which we highly recommend. The clever folks over at [linuxserver.io](https://www.linuxserver.io) have a great image that's easily installed.
I updated this section (well, created two new pages and deleted the old ones). Going to leave the equipment page for another day/PR/contributor.

2023-02-21 01:23 UTC, mikenye approved these changes

2023-02-21 01:23 UTC, merged

2023-02-21 01:23 UTC, mikenye commented
Awesome work, thanks so much @wandering-andy