Update branding/sort on aggregaotors; add page on selecting OS
sdr-enthusiasts/gitbook-adsb-guide pull request #80
Opened 2023-02-22 01:43 UTC by Ottergoose

2023-02-22 03:38 UTC, mikenye commented on README.md
> +These ADS-B data can be received by ~~nerds~~ enthusiasts using Software Defined Radio \(SDR\), and used for fun and profit.
I think it should be "This" as-per the original.

"These ADS-B data" sounds.... weird. :)

We need an English Major :P

2023-02-22 03:46 UTC, mikenye requested changes
Please take a look at the comment on README.md.

Thanks.

2023-02-22 05:25 UTC, tedder commented on README.md
>  * [ADS-B Exchange](https://adsbexchange.com/)
TBH my vote is to not alphasort adsbexchange. Just my opinion.

2023-02-22 06:48 UTC, mikenye commented on README.md
>  * [ADS-B Exchange](https://adsbexchange.com/)
Agree 100% 💯

2023-02-22 18:10 UTC, Ottergoose commented on README.md
> +These ADS-B data can be received by ~~nerds~~ enthusiasts using Software Defined Radio \(SDR\), and used for fun and profit.
It's weird but correct; the word "data" is plural like "chickens" or "geese." Whether or not to always treat it as a plural is a matter of preference.

2023-02-22 18:11 UTC, Ottergoose commented on README.md
>  * [ADS-B Exchange](https://adsbexchange.com/)
What's the preferred method of sorting them?

2023-02-23 01:32 UTC, mikenye commented on README.md
>  * [ADS-B Exchange](https://adsbexchange.com/)
Alphabetical is ok, but stick ADSB Exchange at the bottom. Given recent events I don't really want to promote them...

2023-02-23 02:15 UTC, mikenye approved these changes

2023-02-23 02:15 UTC, merged

2023-02-23 02:15 UTC, mikenye commented
Thanks @Ottergoose and other contributors!